spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webauthN
    username: postgres
    password: toor
    #    driver-class-name: org.postgressql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    #      databases-platform: org.hibernate.dialect.PostgresSQLDialect
    logging:
      level:
        org:
          hibernate:
            type: trace
  #